// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/xuender/poker/game"
)

// Injectors from wire.go:

func InitPoker() *game.Poker {
	bus := game.NewBus()
	start := game.NewStart(bus)
	desktop := game.NewDesktop(bus)
	fonts := game.NewFonts()
	help := game.NewHelp(bus, fonts)
	poker := game.NewPoker(bus, start, desktop, help)
	return poker
}
