// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/xuender/poker/game"
)

// Injectors from wire.go:

func InitPoker() *game.Poker {
	bus := game.NewBus()
	script := game.NewScript(bus)
	startScene := game.NewStart(bus)
	desktopScene := game.NewDesktop(bus, script)
	helpScene := game.NewHelp(bus)
	poker := game.NewPoker(bus, script, startScene, desktopScene, helpScene)
	return poker
}
