// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/xuender/poker/game"
)

// Injectors from wire.go:

func InitPoker() *game.Poker {
	bus := game.NewBus()
	fonts := game.NewFonts()
	startScene := game.NewStart(bus, fonts)
	desktopScene := game.NewDesktop(bus)
	helpScene := game.NewHelp(bus, fonts)
	poker := game.NewPoker(bus, startScene, desktopScene, helpScene)
	return poker
}
