// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: pb/msg_type.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgType TODO: MsgType.
type MsgType int32

const (
	MsgType_ping  MsgType = 0
	MsgType_run   MsgType = 1
	MsgType_reset MsgType = 2
	MsgType_take  MsgType = 3
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "ping",
		1: "run",
		2: "reset",
		3: "take",
	}
	MsgType_value = map[string]int32{
		"ping":  0,
		"run":   1,
		"reset": 2,
		"take":  3,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_msg_type_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_pb_msg_type_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_pb_msg_type_proto_rawDescGZIP(), []int{0}
}

var File_pb_msg_type_proto protoreflect.FileDescriptor

var file_pb_msg_type_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x62, 0x2f, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x2a, 0x31, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03,
	0x72, 0x75, 0x6e, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x72, 0x65, 0x73, 0x65, 0x74, 0x10, 0x02,
	0x12, 0x08, 0x0a, 0x04, 0x74, 0x61, 0x6b, 0x65, 0x10, 0x03, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_msg_type_proto_rawDescOnce sync.Once
	file_pb_msg_type_proto_rawDescData = file_pb_msg_type_proto_rawDesc
)

func file_pb_msg_type_proto_rawDescGZIP() []byte {
	file_pb_msg_type_proto_rawDescOnce.Do(func() {
		file_pb_msg_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_msg_type_proto_rawDescData)
	})
	return file_pb_msg_type_proto_rawDescData
}

var file_pb_msg_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_msg_type_proto_goTypes = []interface{}{
	(MsgType)(0), // 0: pb.MsgType
}
var file_pb_msg_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_msg_type_proto_init() }
func file_pb_msg_type_proto_init() {
	if File_pb_msg_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_msg_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_msg_type_proto_goTypes,
		DependencyIndexes: file_pb_msg_type_proto_depIdxs,
		EnumInfos:         file_pb_msg_type_proto_enumTypes,
	}.Build()
	File_pb_msg_type_proto = out.File
	file_pb_msg_type_proto_rawDesc = nil
	file_pb_msg_type_proto_goTypes = nil
	file_pb_msg_type_proto_depIdxs = nil
}
