// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: pb/scene.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Scene TODO: Scene.
type Scene int32

const (
	Scene_start   Scene = 0
	Scene_desktop Scene = 1
	Scene_help    Scene = 2
)

// Enum value maps for Scene.
var (
	Scene_name = map[int32]string{
		0: "start",
		1: "desktop",
		2: "help",
	}
	Scene_value = map[string]int32{
		"start":   0,
		"desktop": 1,
		"help":    2,
	}
)

func (x Scene) Enum() *Scene {
	p := new(Scene)
	*p = x
	return p
}

func (x Scene) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scene) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_scene_proto_enumTypes[0].Descriptor()
}

func (Scene) Type() protoreflect.EnumType {
	return &file_pb_scene_proto_enumTypes[0]
}

func (x Scene) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Scene.Descriptor instead.
func (Scene) EnumDescriptor() ([]byte, []int) {
	return file_pb_scene_proto_rawDescGZIP(), []int{0}
}

var File_pb_scene_proto protoreflect.FileDescriptor

var file_pb_scene_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x2f, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x2a, 0x29, 0x0a, 0x05, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x12, 0x09, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x6b,
	0x74, 0x6f, 0x70, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x68, 0x65, 0x6c, 0x70, 0x10, 0x02, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_scene_proto_rawDescOnce sync.Once
	file_pb_scene_proto_rawDescData = file_pb_scene_proto_rawDesc
)

func file_pb_scene_proto_rawDescGZIP() []byte {
	file_pb_scene_proto_rawDescOnce.Do(func() {
		file_pb_scene_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_scene_proto_rawDescData)
	})
	return file_pb_scene_proto_rawDescData
}

var file_pb_scene_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_scene_proto_goTypes = []interface{}{
	(Scene)(0), // 0: pb.Scene
}
var file_pb_scene_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_scene_proto_init() }
func file_pb_scene_proto_init() {
	if File_pb_scene_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_scene_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_scene_proto_goTypes,
		DependencyIndexes: file_pb_scene_proto_depIdxs,
		EnumInfos:         file_pb_scene_proto_enumTypes,
	}.Build()
	File_pb_scene_proto = out.File
	file_pb_scene_proto_rawDesc = nil
	file_pb_scene_proto_goTypes = nil
	file_pb_scene_proto_depIdxs = nil
}
